-- ============================================================
-- AutoRD Joselito Auto Import inventory
-- Adds three listings requested from SuperCarros source pages. Prices are
-- stored in DOP because the marketplace currently displays RD$ everywhere.
-- ============================================================

insert into public.dealers
  (name, slug, verified, city, phone, initials, whatsapp, hours, locations, description, rating, rating_count, founded_year)
values
  (
    'Joselito Auto Import',
    'joselito-auto-import',
    true,
    'Santiago',
    '+1 809-724-9999',
    'JA',
    '+1 809-501-5858',
    'Lunes a sábado',
    '[{"name":"Principal","address":"Av. Estrella Sadhalá #172, Centro, Santiago","city":"Santiago","lat":19.4517,"lng":-70.6970}]'::jsonb,
    'Dealer importador en Santiago con inventario premium, atención por WhatsApp y opciones de financiamiento disponibles en AutoRD.',
    4.8,
    94,
    2014
  )
on conflict (slug) do update set
  name = excluded.name,
  verified = excluded.verified,
  city = excluded.city,
  phone = excluded.phone,
  initials = excluded.initials,
  whatsapp = excluded.whatsapp,
  hours = excluded.hours,
  locations = excluded.locations,
  description = excluded.description,
  rating = excluded.rating,
  rating_count = excluded.rating_count,
  founded_year = excluded.founded_year;

with joselito as (
  select id from public.dealers where slug = 'joselito-auto-import'
)
insert into public.vehicles
  (dealer_id, slug, make, model, year, trim, transmission, fuel, engine, mileage, color, body_type,
   price, condition, certified, location, financing, description, features, tone, monthly, apr, term_years,
   status, views, photos_count, lat, lng)
values
  (
    (select id from joselito),
    'lexus-rx-350-f-sport-2022-joselito',
    'Lexus',
    'RX',
    2022,
    '350 F Sport',
    'Automática',
    'Gasolina',
    '6 cilindros',
    0,
    'Blanco',
    'SUV',
    3570000,
    'usado',
    false,
    'Santiago',
    true,
    'Lexus RX 350 F Sport 2022 en blanco con interior rojo, tracción AWD y equipamiento premium. Precio convertido desde US$ 59,500.',
    '["AWD","Apple CarPlay","Asientos en piel","Cámara de reversa","Sensores de parqueo","Sistema de navegación"]'::jsonb,
    '#f8fafc',
    74700,
    9.75,
    7,
    'publicado',
    485,
    12,
    19.4517,
    -70.6970
  ),
  (
    (select id from joselito),
    'toyota-grand-highlander-platinum-hybrid-2024-joselito',
    'Toyota',
    'Grand Highlander',
    2024,
    'Max Platinum Hybrid',
    'Automática',
    'Híbrido',
    '4 cilindros híbrido',
    0,
    'Blanco perla',
    'SUV',
    5130000,
    'usado',
    false,
    'Santiago',
    true,
    'Toyota Grand Highlander Max Platinum Hybrid 2024, 4WD, tres filas y cabina premium en negro. Precio convertido desde US$ 85,500.',
    '["4WD","Híbrido","3 filas","Asientos en piel","Techo panorámico","Sistema de navegación"]'::jsonb,
    '#e5e7eb',
    107300,
    9.75,
    7,
    'publicado',
    393,
    12,
    19.4517,
    -70.6970
  ),
  (
    (select id from joselito),
    'lexus-lx-600-luxury-2024-joselito',
    'Lexus',
    'LX',
    2024,
    '600 Luxury',
    'Automática',
    'Gasolina',
    '6 cilindros',
    0,
    'Blanco perla',
    'SUV',
    9600000,
    'usado',
    false,
    'Santiago',
    true,
    'Lexus LX 600 Luxury 2024, 4WD, tres filas, interior negro y paquete de lujo. Precio convertido desde US$ 160,000.',
    '["4WD","3 filas","Apple CarPlay","Asientos en piel","Cámara de reversa","Sistema de navegación"]'::jsonb,
    '#eef2f7',
    200800,
    9.75,
    7,
    'publicado',
    22,
    7,
    19.4517,
    -70.6970
  )
on conflict (slug) do update set
  dealer_id = excluded.dealer_id,
  make = excluded.make,
  model = excluded.model,
  year = excluded.year,
  trim = excluded.trim,
  transmission = excluded.transmission,
  fuel = excluded.fuel,
  engine = excluded.engine,
  mileage = excluded.mileage,
  color = excluded.color,
  body_type = excluded.body_type,
  price = excluded.price,
  condition = excluded.condition,
  certified = excluded.certified,
  location = excluded.location,
  financing = excluded.financing,
  description = excluded.description,
  features = excluded.features,
  tone = excluded.tone,
  monthly = excluded.monthly,
  apr = excluded.apr,
  term_years = excluded.term_years,
  status = excluded.status,
  views = excluded.views,
  photos_count = excluded.photos_count,
  lat = excluded.lat,
  lng = excluded.lng;
